server:
  port: 8080

logging:
  level:
    donor.blood: debug
    org:
      springframework:
        security: debug

zuul:
  igoredServices: '*'
  sensitiveHeaders: Cookie,Set-Cookie,Authorization
  routes:
    user-service:
      path: /user-service/**
      stripPrefix: true
    #    auth:
    #      path: /auth/**
    #      url: http://localhost:8980/auth
    #      stripPrefix: true
    blood-supplies-service:
      path: /blood-supplies/**
      stripPrefix: true
    web:
      path: /**
      stripPrefix: false

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  eureka:
    enabled: false

user-service:
  ribbon:
    listOfServers: localhost:2222
blood-supplies-service:
  ribbon:
    listOfServers: localhost:1111
web:
  ribbon:
    listOfServers: localhost:4200
